/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javamaster.oop;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author denise, aira, zach
 */
public class EmployeeDashboard extends javax.swing.JFrame {
    private Employee emp;
    private List<String[]> leaveDatabase;
    /**
     * Creates new form EmployeeDashboard
     */
    public EmployeeDashboard(Employee emp) {
        this.emp=emp;
        initComponents();
        
        this.leaveDatabase = emp.loadCSV("LeaveManagement.csv");
         
        ////Dashboard Panel Display
        jTextDashboardEmpNo.setText(emp.getEmployeeId());
        jTextDashboardFirstName.setText(emp.getFirstName());
        jTextDashboardLastName.setText(emp.getLastName());
        jAreaDashboardAddress.setText(emp.getAddress());
        jTextDashboardBirthday.setText(emp.getBirthday());
        jTextDashboardPhoneNo.setText(emp.getPhoneNumber());
        jTextDashboardStatus.setText(emp.getStatus());
        jTextDashboardPosition.setText(emp.getPosition());
        jTextDashboardSupervisor.setText(emp.getStatus());
        jTextDashboardTinNum.setText(emp.getPosition());
        jTextDashboardSupervisor.setText(emp.getImmediateSupervisor());
        jTextDashboardSssNum.setText(emp.getSssNumber());
        jTextDashboardPhilhealthNum.setText(emp.getPhilhealthNumber());
        jTextDashboardPagibigNum.setText(emp.getPagIbigNumber());
        jTextDashboardTinNum.setText(emp.getTinNumber());
        jTextDashboardRiceSubsidy.setText(Double.toString(emp.getRiceSubsidy()));
        jTextDashboardPhoneAllowance.setText(Double.toString(emp.getPhoneAllowance()));
        jTextDashboardClothingAllowance.setText(Double.toString(emp.getClothingAllowance()));
        jTextDashboardHourlyRate.setText(Double.toString(emp.getHourlyRate()));
        jTextDashboardGrossSemiMonthlyRate.setText(Double.toString(emp.getGrossSemiMonthlyRate()));
        jTextDashboardBasicSalary.setText(Double.toString(emp.getBasicSalary()));
        
        // set text for request details
        jTextLeaveEmpNo.setText(emp.getEmployeeId());
        jTextLeaveFirstName.setText(emp.getFirstName());
        jTextLeaveLastName.setText(emp.getLastName());
        jTextLeavePosition.setText(emp.getPosition());
        
        Date fromDate = jCalendarStart.getDate();
        Date toDate = jCalendarEnd.getDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(toDate);
        calendar.add(Calendar.DAY_OF_MONTH, 1);
        toDate = calendar.getTime();
        jCalendarEnd.setDate(toDate);
        
        
        
        
        
        
        
        
        
        
        
        // comment
  
    }
  
    //comment sa branch
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        dashboardMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        salaryCalculationMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fileLeaveMenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jPanelParent = new javax.swing.JPanel();
        jPanelDashboard = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextDashboardPhoneNo = new javax.swing.JTextField();
        jTextDashboardBirthday = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAreaDashboardAddress = new javax.swing.JTextArea();
        jTextDashboardLastName = new javax.swing.JTextField();
        jTextDashboardFirstName = new javax.swing.JTextField();
        jTextDashboardEmpNo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextDashboardTinNum = new javax.swing.JTextField();
        jTextDashboardPagibigNum = new javax.swing.JTextField();
        jTextDashboardPhilhealthNum = new javax.swing.JTextField();
        jTextDashboardSssNum = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextDashboardRiceSubsidy = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jTextDashboardPhoneAllowance = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextDashboardClothingAllowance = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jTextDashboardHourlyRate = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextDashboardGrossSemiMonthlyRate = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextDashboardBasicSalary = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jTextDashboardStatus = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jTextDashboardSupervisor = new javax.swing.JTextField();
        jTextDashboardPosition = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jPanelSalaryCalculation = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextSalaryStatus = new javax.swing.JTextField();
        jTextSalaryPosition = new javax.swing.JTextField();
        jTextSalarySupervisor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextSalarySssNum = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextSalaryPagibigNum = new javax.swing.JTextField();
        jTextSalaryTin = new javax.swing.JTextField();
        jTextSalaryPhilhealthNum = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextSalaryBirthday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextSalaryPhoneNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextSalaryEmpNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextSalaryLastName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextSalaryFirstName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jAreaSalaryAddress = new javax.swing.JTextArea();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldBasicSalary = new javax.swing.JTextField();
        jTextFieldGrossSemiMonthlyRate = new javax.swing.JTextField();
        jTextFieldHourlyRate = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldSSSContribution = new javax.swing.JTextField();
        jTextFieldPhilHealthContribution = new javax.swing.JTextField();
        jTextFieldPagIBIGContribution = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldGrossPay = new javax.swing.JTextField();
        jTextFieldNetPay = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldRiceSubsidy = new javax.swing.JTextField();
        jTextFieldPhoneAllowance = new javax.swing.JTextField();
        jTextFieldClothingAllowance = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButtonComputeSalary = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jPanelFileLeave = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jComboBoxLeaveType = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextLeaveEmpNo = new javax.swing.JTextField();
        jTextLeaveFirstName = new javax.swing.JTextField();
        jTextLeaveLastName = new javax.swing.JTextField();
        jTextLeavePosition = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jCalendarStart = new com.toedter.calendar.JCalendar();
        jCalendarEnd = new com.toedter.calendar.JCalendar();
        jButtonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1250, 775));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 750));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1500, 750));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MotorPH");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payroll System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 70));

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardMenu.setBackground(new java.awt.Color(51, 51, 51));
        dashboardMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        dashboardMenu.setForeground(new java.awt.Color(51, 51, 51));
        dashboardMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMenuMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");
        jLabel3.setPreferredSize(new java.awt.Dimension(406, 320));

        javax.swing.GroupLayout dashboardMenuLayout = new javax.swing.GroupLayout(dashboardMenu);
        dashboardMenu.setLayout(dashboardMenuLayout);
        dashboardMenuLayout.setHorizontalGroup(
            dashboardMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardMenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        dashboardMenuLayout.setVerticalGroup(
            dashboardMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardMenuLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel3.add(dashboardMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 60));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 14));

        salaryCalculationMenu.setBackground(new java.awt.Color(153, 0, 0));
        salaryCalculationMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        salaryCalculationMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaryCalculationMenuMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Salary Calculation");

        javax.swing.GroupLayout salaryCalculationMenuLayout = new javax.swing.GroupLayout(salaryCalculationMenu);
        salaryCalculationMenu.setLayout(salaryCalculationMenuLayout);
        salaryCalculationMenuLayout.setHorizontalGroup(
            salaryCalculationMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaryCalculationMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        salaryCalculationMenuLayout.setVerticalGroup(
            salaryCalculationMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaryCalculationMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.add(salaryCalculationMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 60));

        fileLeaveMenu.setBackground(new java.awt.Color(153, 0, 0));
        fileLeaveMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        fileLeaveMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileLeaveMenuMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("File Leave");

        javax.swing.GroupLayout fileLeaveMenuLayout = new javax.swing.GroupLayout(fileLeaveMenu);
        fileLeaveMenu.setLayout(fileLeaveMenuLayout);
        fileLeaveMenuLayout.setHorizontalGroup(
            fileLeaveMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLeaveMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        fileLeaveMenuLayout.setVerticalGroup(
            fileLeaveMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLeaveMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.add(fileLeaveMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, -1));

        jButtonLogout.setBackground(new java.awt.Color(102, 0, 0));
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 680));

        jPanelParent.setBackground(new java.awt.Color(51, 51, 51));
        jPanelParent.setPreferredSize(new java.awt.Dimension(1200, 750));
        jPanelParent.setLayout(new java.awt.CardLayout());

        jPanelDashboard.setBackground(new java.awt.Color(51, 51, 51));
        jPanelDashboard.setPreferredSize(new java.awt.Dimension(950, 700));
        jPanelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Employee No. :");
        jPanel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("First Name :");
        jPanel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Last Name :");
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Address :");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Birthday :");
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Phone No. :");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 70, 20));

        jTextDashboardPhoneNo.setEditable(false);
        jPanel5.add(jTextDashboardPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 120, -1));

        jTextDashboardBirthday.setEditable(false);
        jPanel5.add(jTextDashboardBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 120, -1));

        jAreaDashboardAddress.setColumns(20);
        jAreaDashboardAddress.setLineWrap(true);
        jAreaDashboardAddress.setRows(5);
        jScrollPane2.setViewportView(jAreaDashboardAddress);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 200, 50));

        jTextDashboardLastName.setEditable(false);
        jPanel5.add(jTextDashboardLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, -1));

        jTextDashboardFirstName.setEditable(false);
        jPanel5.add(jTextDashboardFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, -1));

        jTextDashboardEmpNo.setEditable(false);
        jPanel5.add(jTextDashboardEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 60, -1));

        jPanelDashboard.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 455, 363));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextDashboardTinNum.setEditable(false);
        jPanel6.add(jTextDashboardTinNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 190, -1));

        jTextDashboardPagibigNum.setEditable(false);
        jPanel6.add(jTextDashboardPagibigNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 190, -1));

        jTextDashboardPhilhealthNum.setEditable(false);
        jPanel6.add(jTextDashboardPhilhealthNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 190, -1));

        jTextDashboardSssNum.setEditable(false);
        jPanel6.add(jTextDashboardSssNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 190, -1));

        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("SSS No. :");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 20));

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("PhilHealth No. :");
        jPanel6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("PagIBIG No. :");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("TIN :");
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jPanelDashboard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 435, 180));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextDashboardRiceSubsidy.setEditable(false);
        jPanel7.add(jTextDashboardRiceSubsidy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 190, -1));

        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Rice Subsidy :");
        jPanel7.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        jTextDashboardPhoneAllowance.setEditable(false);
        jPanel7.add(jTextDashboardPhoneAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 190, -1));

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Phone Allowance :");
        jPanel7.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Clothing Allowance :");
        jPanel7.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        jTextDashboardClothingAllowance.setEditable(false);
        jPanel7.add(jTextDashboardClothingAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 190, -1));

        jPanelDashboard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 435, 173));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextDashboardHourlyRate.setEditable(false);
        jPanel8.add(jTextDashboardHourlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, -1));

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Hourly Rate :");
        jPanel8.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Gross Semi-monthly Rate : ");
        jPanel8.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        jTextDashboardGrossSemiMonthlyRate.setEditable(false);
        jPanel8.add(jTextDashboardGrossSemiMonthlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, -1));

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Basic Salary :");
        jPanel8.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        jTextDashboardBasicSalary.setEditable(false);
        jPanel8.add(jTextDashboardBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 190, -1));

        jPanelDashboard.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 435, 170));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Position : ");
        jPanel9.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        jTextDashboardStatus.setEditable(false);
        jPanel9.add(jTextDashboardStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, -1));

        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Status :");
        jPanel9.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Immediate Supervisor : ");
        jPanel9.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jTextDashboardSupervisor.setEditable(false);
        jPanel9.add(jTextDashboardSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 190, -1));

        jTextDashboardPosition.setEditable(false);
        jPanel9.add(jTextDashboardPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, -1));

        jPanelDashboard.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 455, 179));

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Employee Dashboard");
        jPanelDashboard.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 220, 40));

        jPanelParent.add(jPanelDashboard, "card3");

        jPanelSalaryCalculation.setBackground(new java.awt.Color(51, 51, 51));
        jPanelSalaryCalculation.setMinimumSize(new java.awt.Dimension(980, 640));
        jPanelSalaryCalculation.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanelSalaryCalculation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(51, 51, 51));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Status :");
        jPanel19.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Position :");
        jPanel19.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 90, 20));

        jTextSalaryStatus.setEditable(false);
        jPanel19.add(jTextSalaryStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 170, -1));

        jTextSalaryPosition.setEditable(false);
        jPanel19.add(jTextSalaryPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 170, -1));

        jTextSalarySupervisor.setEditable(false);
        jPanel19.add(jTextSalarySupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 170, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SSS No. :");
        jPanel19.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 60, 20));

        jTextSalarySssNum.setEditable(false);
        jPanel19.add(jTextSalarySssNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 140, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PhilHealth No. :");
        jPanel19.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 90, 20));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TIN :");
        jPanel19.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 60, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pag-IBIG No. :");
        jPanel19.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 90, 20));

        jTextSalaryPagibigNum.setEditable(false);
        jPanel19.add(jTextSalaryPagibigNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 140, -1));

        jTextSalaryTin.setEditable(false);
        jPanel19.add(jTextSalaryTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 140, -1));

        jTextSalaryPhilhealthNum.setEditable(false);
        jPanel19.add(jTextSalaryPhilhealthNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 140, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Immediate Supervisor :");
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 130, 20));

        jTextSalaryBirthday.setEditable(false);
        jPanel19.add(jTextSalaryBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 170, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Birthday :");
        jPanel19.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jTextSalaryPhoneNo.setEditable(false);
        jPanel19.add(jTextSalaryPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 170, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone No. :");
        jPanel19.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 100, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee No. : ");
        jPanel19.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 20));

        jTextSalaryEmpNo.setEditable(false);
        jTextSalaryEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSalaryEmpNoActionPerformed(evt);
            }
        });
        jPanel19.add(jTextSalaryEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last Name : ");
        jPanel19.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jTextSalaryLastName.setEditable(false);
        jPanel19.add(jTextSalaryLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 210, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("First Name :");
        jPanel19.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jTextSalaryFirstName.setEditable(false);
        jPanel19.add(jTextSalaryFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 210, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Address :");
        jPanel19.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 20));

        jAreaSalaryAddress.setEditable(false);
        jAreaSalaryAddress.setColumns(20);
        jAreaSalaryAddress.setLineWrap(true);
        jAreaSalaryAddress.setRows(5);
        jScrollPane3.setViewportView(jAreaSalaryAddress);

        jPanel19.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 210, 50));

        jPanelSalaryCalculation.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1000, 180));

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthActionPerformed(evt);
            }
        });
        jPanelSalaryCalculation.add(jComboBoxMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 100, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Select Month");
        jPanelSalaryCalculation.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 100, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Earnings");
        jPanelSalaryCalculation.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 70, 20));

        jTextFieldBasicSalary.setEditable(false);
        jPanelSalaryCalculation.add(jTextFieldBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 270, -1));

        jTextFieldGrossSemiMonthlyRate.setEditable(false);
        jPanelSalaryCalculation.add(jTextFieldGrossSemiMonthlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 270, -1));

        jTextFieldHourlyRate.setEditable(false);
        jTextFieldHourlyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourlyRateActionPerformed(evt);
            }
        });
        jPanelSalaryCalculation.add(jTextFieldHourlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 270, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Hourly Rate :");
        jPanelSalaryCalculation.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gross Semi-Monthly Rate :");
        jPanelSalaryCalculation.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 160, 20));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Basic Salary :");
        jPanelSalaryCalculation.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 100, 20));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("SSS Contribution :");
        jPanelSalaryCalculation.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 110, 20));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("PhilHealth Contribution :");
        jPanelSalaryCalculation.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 140, 20));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Pag-IBIG Contribution :");
        jPanelSalaryCalculation.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 150, 20));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Deductions");
        jPanelSalaryCalculation.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 90, 20));

        jTextFieldSSSContribution.setEditable(false);
        jTextFieldSSSContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSSSContributionActionPerformed(evt);
            }
        });
        jPanelSalaryCalculation.add(jTextFieldSSSContribution, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 270, -1));

        jTextFieldPhilHealthContribution.setEditable(false);
        jTextFieldPhilHealthContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhilHealthContributionActionPerformed(evt);
            }
        });
        jPanelSalaryCalculation.add(jTextFieldPhilHealthContribution, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 270, -1));

        jTextFieldPagIBIGContribution.setEditable(false);
        jTextFieldPagIBIGContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPagIBIGContributionActionPerformed(evt);
            }
        });
        jPanelSalaryCalculation.add(jTextFieldPagIBIGContribution, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 270, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Total");
        jPanelSalaryCalculation.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 100, 20));

        jTextFieldGrossPay.setEditable(false);
        jPanelSalaryCalculation.add(jTextFieldGrossPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 270, -1));

        jTextFieldNetPay.setEditable(false);
        jPanelSalaryCalculation.add(jTextFieldNetPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 270, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Net Pay :");
        jPanelSalaryCalculation.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 100, 20));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Gross Pay :");
        jPanelSalaryCalculation.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 100, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Allowances");
        jPanelSalaryCalculation.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 100, 20));

        jTextFieldRiceSubsidy.setEditable(false);
        jPanelSalaryCalculation.add(jTextFieldRiceSubsidy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 270, -1));

        jTextFieldPhoneAllowance.setEditable(false);
        jPanelSalaryCalculation.add(jTextFieldPhoneAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 270, -1));

        jTextFieldClothingAllowance.setEditable(false);
        jPanelSalaryCalculation.add(jTextFieldClothingAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 270, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Clothing Allowance :");
        jPanelSalaryCalculation.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 140, 20));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Phone Allowance :");
        jPanelSalaryCalculation.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 110, 20));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Rice Subsidy :");
        jPanelSalaryCalculation.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 90, 20));

        jButtonComputeSalary.setBackground(new java.awt.Color(102, 102, 102));
        jButtonComputeSalary.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComputeSalary.setText("Compute");
        jButtonComputeSalary.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonComputeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputeSalaryActionPerformed(evt);
            }
        });
        jPanelSalaryCalculation.add(jButtonComputeSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, 160, 40));

        jLabel44.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Employee Salary Calculation");
        jPanelSalaryCalculation.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 300, 40));

        jPanelParent.add(jPanelSalaryCalculation, "card2");

        jPanelFileLeave.setBackground(new java.awt.Color(51, 51, 51));
        jPanelFileLeave.setMinimumSize(new java.awt.Dimension(980, 680));
        jPanelFileLeave.setPreferredSize(new java.awt.Dimension(980, 680));
        jPanelFileLeave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Employee No. :");
        jPanelFileLeave.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 20));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("First Name :");
        jPanelFileLeave.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 20));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Last Name :");
        jPanelFileLeave.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Position :");
        jPanelFileLeave.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, 20));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Leave Type :");
        jPanelFileLeave.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 20));

        jComboBoxLeaveType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sick Leave", "Vacation Leave", "Bereavement Leave", "Ano pa ba" }));
        jComboBoxLeaveType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLeaveTypeActionPerformed(evt);
            }
        });
        jPanelFileLeave.add(jComboBoxLeaveType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 270, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Date :");
        jPanelFileLeave.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, 20));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Start Date");
        jPanelFileLeave.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 20));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Date of Return");
        jPanelFileLeave.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, 20));
        jPanelFileLeave.add(jTextLeaveEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 270, -1));
        jPanelFileLeave.add(jTextLeaveFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 270, -1));
        jPanelFileLeave.add(jTextLeaveLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 270, -1));
        jPanelFileLeave.add(jTextLeavePosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 270, -1));

        jLabel43.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Leave Request Form");
        jPanelFileLeave.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, 30));
        jPanelFileLeave.add(jCalendarStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 270, 190));
        jPanelFileLeave.add(jCalendarEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 270, 190));

        jButtonSubmit.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("Submit");
        jButtonSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanelFileLeave.add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, 120, 30));

        jPanelParent.add(jPanelFileLeave, "card4");

        jPanel1.add(jPanelParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 680));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSalaryEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSalaryEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSalaryEmpNoActionPerformed

    private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMonthActionPerformed

    private void jTextFieldHourlyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourlyRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourlyRateActionPerformed

    private void jTextFieldSSSContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSSSContributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSSSContributionActionPerformed

    private void jTextFieldPhilHealthContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhilHealthContributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhilHealthContributionActionPerformed

    private void jTextFieldPagIBIGContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPagIBIGContributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPagIBIGContributionActionPerformed

    private void jButtonComputeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputeSalaryActionPerformed
        // TODO add your handling code here:
       String month = (String) jComboBoxMonth.getSelectedItem();

    // Recalculate payroll
    
    double[] payrollData = emp.CalculatePayroll(emp, month);  // Ensure payroll is recalculated

    // Update text fields
    jTextFieldBasicSalary.setText(Double.toString(emp.getBasicSalary()));
    jTextFieldGrossSemiMonthlyRate.setText(Double.toString(emp.getGrossSemiMonthlyRate()));
    jTextFieldHourlyRate.setText(Double.toString(emp.getHourlyRate()));

    jTextFieldSSSContribution.setText(Double.toString(payrollData[3]));
    jTextFieldPhilHealthContribution.setText(Double.toString(payrollData[4]));
    jTextFieldPagIBIGContribution.setText(Double.toString(payrollData[5]));
    jTextFieldGrossPay.setText(Double.toString(payrollData[0]));
    jTextFieldNetPay.setText(Double.toString(payrollData[9]));
       System.out.println("Witholding tax: " + payrollData[6]);
       
       
       
       
       
       
    }//GEN-LAST:event_jButtonComputeSalaryActionPerformed

    private void jComboBoxLeaveTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLeaveTypeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxLeaveTypeActionPerformed

    private void dashboardMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMenuMouseClicked
        // TODO add your handling code here:
        dashboardMenu.setBackground(new Color (51,51,51));
        salaryCalculationMenu.setBackground(new Color (153,0,0));
        fileLeaveMenu.setBackground(new Color (153,0,0));
        jPanelParent.removeAll();
        jPanelParent.add(jPanelDashboard);
        jPanelParent.repaint();
        jPanelParent.revalidate();
    }//GEN-LAST:event_dashboardMenuMouseClicked

    private void salaryCalculationMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryCalculationMenuMouseClicked
        // TODO add your handling code here:
        salaryCalculationMenu.setBackground(new Color (51,51,51));
        dashboardMenu.setBackground(new Color (153,0,0));
        fileLeaveMenu.setBackground(new Color (153,0,0));
        jPanelParent.removeAll();
        jPanelParent.add(jPanelSalaryCalculation);
        jPanelParent.repaint();
        jPanelParent.revalidate();
        
        //Salary Calculation Panel
        jTextSalaryEmpNo.setText(emp.getEmployeeId());
        jTextSalaryFirstName.setText(emp.getFirstName());
        jTextSalaryLastName.setText(emp.getLastName());
        jAreaSalaryAddress.setText(emp.getAddress());
        jTextSalaryBirthday.setText(emp.getBirthday());
        jTextSalaryPhoneNo.setText(emp.getPhoneNumber());
        jTextSalaryStatus.setText(emp.getStatus());
        jTextSalaryPosition.setText(emp.getPosition());
        jTextSalarySupervisor.setText(emp.getStatus());
        jTextSalaryTin.setText(emp.getPosition());
        jTextSalarySupervisor.setText(emp.getImmediateSupervisor());
        jTextSalarySssNum.setText(emp.getSssNumber());
        jTextSalaryPhilhealthNum.setText(emp.getPhilhealthNumber());
        jTextSalaryPagibigNum.setText(emp.getPagIbigNumber());
        jTextSalaryTin.setText(emp.getTinNumber());
    }//GEN-LAST:event_salaryCalculationMenuMouseClicked

    private void fileLeaveMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileLeaveMenuMouseClicked
        // TODO add your handling code here:
        fileLeaveMenu.setBackground(new Color (51,51,51));
        dashboardMenu.setBackground(new Color (153,0,0));
        salaryCalculationMenu.setBackground(new Color (153,0,0));
        jPanelParent.removeAll();
        jPanelParent.add(jPanelFileLeave);
        jPanelParent.repaint();
        jPanelParent.revalidate();
        
        //Salary Calculation Panel
        jTextSalaryEmpNo.setText(emp.getEmployeeId());
        jTextSalaryFirstName.setText(emp.getFirstName());
        jTextSalaryLastName.setText(emp.getLastName());
        jAreaSalaryAddress.setText(emp.getAddress());
        jTextSalaryBirthday.setText(emp.getBirthday());
        jTextSalaryPhoneNo.setText(emp.getPhoneNumber());
        jTextSalaryStatus.setText(emp.getStatus());
        jTextSalaryPosition.setText(emp.getPosition());
        jTextSalarySupervisor.setText(emp.getStatus());
        jTextSalaryTin.setText(emp.getPosition());
        jTextSalarySupervisor.setText(emp.getImmediateSupervisor());
        jTextSalarySssNum.setText(emp.getSssNumber());
        jTextSalaryPhilhealthNum.setText(emp.getPhilhealthNumber());
        jTextSalaryPagibigNum.setText(emp.getPagIbigNumber());
        jTextSalaryTin.setText(emp.getTinNumber());
    }//GEN-LAST:event_fileLeaveMenuMouseClicked

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed

        // array for the leave data
        String[] leaveData = new String[9];
        leaveData[0] = Integer.toString(leaveDatabase.size() + 1); // request #
        leaveData[1] = emp.getEmployeeId();
        leaveData[2] = emp.getFirstName();
        leaveData[3] = emp.getLastName();
        leaveData[4] = emp.getPosition();
        leaveData[5] = (String) jComboBoxLeaveType.getSelectedItem();
        leaveData[8] = "Pending"; // status
        
        // Validate Dates
        // get current date
        Calendar today = Calendar.getInstance();
        Date currentDate = today.getTime();
        // start date
        Date startDate = jCalendarStart.getDate();
        // end date
        Date endDate = jCalendarEnd.getDate();
        
        
        StringBuilder validationMessage = new StringBuilder();
        // check if start date is in the past / today
        if (startDate.before(currentDate) || startDate.equals(currentDate)) {
            validationMessage.append("The inputted start date is invalid.\n");
        }
        // check if end date is before start date / today / in the past
        if (endDate.before(startDate) || startDate.equals(currentDate) || endDate.before(currentDate)) {
            validationMessage.append("The inputted end date is invalid.");
        }
        
        if (validationMessage.length() > 0) {
            JOptionPane.showMessageDialog(this, validationMessage.toString()); // show error(s) if there's any
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            leaveData[6] = sdf.format( jCalendarStart.getDate()); // start date of leave
            leaveData[7] = sdf.format(jCalendarEnd.getDate()); // end date

            emp.fileLeave(leaveData, leaveDatabase, "LeaveManagement.csv"); // add array to csv file
            JOptionPane.showMessageDialog(this, "Your leave request has been successfully filed.");
        }



    }//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnidentifiedUser unidentifiedUser = new UnidentifiedUser();
                unidentifiedUser.setRole("Employee");
                
                LoginValidator lv = new LoginValidator();
                lv.openDashboard(unidentifiedUser);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardMenu;
    private javax.swing.JPanel fileLeaveMenu;
    private javax.swing.JTextArea jAreaDashboardAddress;
    private javax.swing.JTextArea jAreaSalaryAddress;
    private javax.swing.JButton jButtonComputeSalary;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSubmit;
    private com.toedter.calendar.JCalendar jCalendarEnd;
    private com.toedter.calendar.JCalendar jCalendarStart;
    private javax.swing.JComboBox<String> jComboBoxLeaveType;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JPanel jPanelFileLeave;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JPanel jPanelSalaryCalculation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextDashboardBasicSalary;
    private javax.swing.JTextField jTextDashboardBirthday;
    private javax.swing.JTextField jTextDashboardClothingAllowance;
    private javax.swing.JTextField jTextDashboardEmpNo;
    private javax.swing.JTextField jTextDashboardFirstName;
    private javax.swing.JTextField jTextDashboardGrossSemiMonthlyRate;
    private javax.swing.JTextField jTextDashboardHourlyRate;
    private javax.swing.JTextField jTextDashboardLastName;
    private javax.swing.JTextField jTextDashboardPagibigNum;
    private javax.swing.JTextField jTextDashboardPhilhealthNum;
    private javax.swing.JTextField jTextDashboardPhoneAllowance;
    private javax.swing.JTextField jTextDashboardPhoneNo;
    private javax.swing.JTextField jTextDashboardPosition;
    private javax.swing.JTextField jTextDashboardRiceSubsidy;
    private javax.swing.JTextField jTextDashboardSssNum;
    private javax.swing.JTextField jTextDashboardStatus;
    private javax.swing.JTextField jTextDashboardSupervisor;
    private javax.swing.JTextField jTextDashboardTinNum;
    private javax.swing.JTextField jTextFieldBasicSalary;
    private javax.swing.JTextField jTextFieldClothingAllowance;
    private javax.swing.JTextField jTextFieldGrossPay;
    private javax.swing.JTextField jTextFieldGrossSemiMonthlyRate;
    private javax.swing.JTextField jTextFieldHourlyRate;
    private javax.swing.JTextField jTextFieldNetPay;
    private javax.swing.JTextField jTextFieldPagIBIGContribution;
    private javax.swing.JTextField jTextFieldPhilHealthContribution;
    private javax.swing.JTextField jTextFieldPhoneAllowance;
    private javax.swing.JTextField jTextFieldRiceSubsidy;
    private javax.swing.JTextField jTextFieldSSSContribution;
    private javax.swing.JTextField jTextLeaveEmpNo;
    private javax.swing.JTextField jTextLeaveFirstName;
    private javax.swing.JTextField jTextLeaveLastName;
    private javax.swing.JTextField jTextLeavePosition;
    private javax.swing.JTextField jTextSalaryBirthday;
    private javax.swing.JTextField jTextSalaryEmpNo;
    private javax.swing.JTextField jTextSalaryFirstName;
    private javax.swing.JTextField jTextSalaryLastName;
    private javax.swing.JTextField jTextSalaryPagibigNum;
    private javax.swing.JTextField jTextSalaryPhilhealthNum;
    private javax.swing.JTextField jTextSalaryPhoneNo;
    private javax.swing.JTextField jTextSalaryPosition;
    private javax.swing.JTextField jTextSalarySssNum;
    private javax.swing.JTextField jTextSalaryStatus;
    private javax.swing.JTextField jTextSalarySupervisor;
    private javax.swing.JTextField jTextSalaryTin;
    private javax.swing.JPanel salaryCalculationMenu;
    // End of variables declaration//GEN-END:variables
}
